### ISSUE TITLE
Deleting UCS files after 10d age.

### ISSUE THREAD

**Issue by rebarali** [megamattzilla/ansible#1]
Hello Matt, thanks for putting this together. Everything works great except the script cannot delete ucs_files after 10 days of retention. It would be great to help me out there.

**Comment by rebarali** [comment]
never mind, I removed quote from [ when: 'remove_old_ucs == true' ]. It solved the issue :)

**Comment by megamattzilla** [comment]
Hi Rebar, Hope all is well! 

Thanks for the feedback- there was a syntax issue in the UCS remove code. 

I posted a new commit that fixes the issue. https://github.com/megamattzilla/ansible/commit/17147e112df7761b0d82b2a89353b84929c4f47b 

Let me know if you see any other issues.

Thanks!

**Comment by rebarali** [comment]
Hi Matt,
Thank you for posting a new commit. It works great as expected when I run ansible manually. However, files won't get deleted if ansible runs through scheduled Cron jobs.
Thank you
